
FROM node

WORKDIR /client/

COPY /packages/client/package.json ./
COPY /packages/client/tsconfig* ./

COPY /packages/client ./

EXPOSE $CLIENT_PORT

RUN yarn install && yarn global add typescript --dev && yarn global add vite --dev && yarn build:docker

CMD yarn dev