FROM node

WORKDIR /client/

COPY /packages/client/package.json ./
COPY /packages/client/tsconfig* ./

RUN npm install
RUN npm install --save-dev -g typescript
RUN npm install --save-dev -g vite

COPY /packages/client ./

EXPOSE $CLIENT_PORT

RUN yarn build:docker

CMD yarn dev