version: "3.3"

services:
  client:
    tty: true
    container_name: client
    build:
      context: .
      dockerfile: Dockerfile.client
      args:
        CLIENT_PORT: ${CLIENT_PORT}
    depends_on:
      - postgres
    ports:
      - "${CLIENT_PORT}:${CLIENT_PORT}"
    environment:
      CLIENT_PORT: ${CLIENT_PORT}
    env_file:
      ./.env.sample
    networks:
      - network_bridge

  ssrapp:
    tty: true
    container_name: ssrapp
    build:
      context: .
      dockerfile: Dockerfile.server
      args:
        SERVER_PORT: ${SERVER_PORT}
    depends_on:
      - postgres
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
    environment:
      - SERVER_PORT=${SERVER_PORT}
    env_file:
      ./.env.sample
    networks:
      - network_bridge

  postgres:
    image: postgres:14
    ports:
      - "8432:${POSTGRES_PORT}"
    volumes:
      - ./postgresdata:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    env_file:
      ./.env.sample
    networks:
      - network_bridge

networks:
  network_bridge:
    driver: bridge